CREATE TABLE IF NOT EXISTS cash_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kid_name VARCHAR(255),
    balance DECIMAL(19, 2),
    issue_date DATE,
    expiry_date DATE,
    parent_name VARCHAR(255)
);